### ISSUE TITLE
Printing api URL disturbs target application

### ISSUE THREAD

**Issue by xhujerr** [bkjones/pyrabbit#34]
Method `HTTPClient.do_call()` ([http.py, line 101](https://github.com/bkjones/pyrabbit/blob/master/pyrabbit/http.py#L101)) unconditionally echoes url. I use pyrabbit in an agent which catches and parses stdout. Echoed url causes error since is unexpected by the agent.

I see two possible solutions:

1) The `url` is a debug message and thus it shall be removed.
2) The `url` printing is useful somehow. Then the client class shall have option `silent=False`. If set to true, the `url` won't be echoed.

**Comment by xhujerr** [comment]
Ok. Now I see there are already several merge requests for this bug. The least intrusive from [jofusa](https://github.com/bkjones/pyrabbit/pull/27).

Can you merge that please?

**Comment by stephane-martin** [comment]
+1, please :)

**Comment by ricardoklein** [comment]
+1

**Comment by Rajlaxmi** [comment]
+1

**Comment by rnt** [comment]
+1

**Comment by sclooney94** [comment]
Hi I'm still having this issue with the latest pip install of pyrabbit (1.1.0). Everytime I use the client it prints the url, when I use "pip install -U git+https://github.com/bkjones/pyrabbit.git" it removes this issue but I then get;

Traceback (most recent call last):
  File "messages.py", line 13, in <module>
    all_queue_names = [str(q['name']) for q in cl.get_queues()]
  File "/home/anaconda2/lib/python2.7/site-packages/pyrabbit/api.py", line 478, in get_queues
    queues = self._call(path, 'GET')
  File "/home/anaconda2/lib/python2.7/site-packages/pyrabbit/api.py", line 108, in _call
    resp = self.http.do_call(path, method, body, headers)
  File "/home/anaconda2/lib/python2.7/site-packages/pyrabbit/http.py", line 102, in do_call
    raise HTTPError(content, resp.status_code, resp.text, path, body)
pyrabbit.http.HTTPError: 404 - Not found. (None) (queues) (None)

This appear when trying to run a very basic code ?

from pyrabbit.api import Client

cl = Client('localhost:15672', 'guest', 'guest')
all_queue_names = [str(q['name']) for q in cl.get_queues()]

any help would be greatly appreciated

**Comment by morganchristiansson** [comment]
+1

This is fixed in master but not latest v1.1.0 release https://github.com/bkjones/pyrabbit/blob/v1.1.0/pyrabbit/http.py#L101

I'm redirecting stdout to /dev/null as a workaround ` >/dev/null`

**Comment by ShibaBandit** [comment]
+1

**Comment by deslum** [comment]
I fork and update module. Welcome https://github.com/deslum/pyrabbit2
